"""AI Provenance utility for EU AI Act Article 50 transparency compliance.

Every API response containing AI-generated content must include provenance
metadata identifying the content as AI-generated, the model used, and the
provider.  This module provides the shared data model and helper functions
used across all AI-facing endpoints.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel

from app.config.settings import settings


class AIProvenance(BaseModel):
    """Article 50 transparency metadata attached to AI-generated responses."""

    ai_generated: bool = True
    model: str  # e.g. "claude-sonnet-4-20250514", "lstm-chiller-v1"
    provider: str  # e.g. "anthropic", "sentinel-local"
    disclosure: str = (
        "This content was generated by an AI system (SENTINEL). "
        "It should be reviewed by qualified personnel before acting on it."
    )
    correlation_id: str | None = None
    app_version: str = settings.app_version
    config_checksum: str = settings.config_checksum


# ---------------------------------------------------------------------------
# Convenience constructors
# ---------------------------------------------------------------------------


def get_claude_provenance(correlation_id: str | None = None) -> AIProvenance:
    """Return provenance for Claude-generated content (chat, explanations)."""
    return AIProvenance(
        model="claude-sonnet-4-20250514",
        provider="anthropic",
        correlation_id=correlation_id,
    )


def get_local_llm_provenance(
    model: str = "phi3:mini",
    correlation_id: str | None = None,
) -> AIProvenance:
    """Return provenance for local LLM-generated content (Ollama/local runtime)."""
    return AIProvenance(
        model=model,
        provider="sentinel-local",
        correlation_id=correlation_id,
    )


def get_cloud_llm_provenance(
    provider: str,
    model: str,
    correlation_id: str | None = None,
) -> AIProvenance:
    """Return provenance for cloud LLM-generated content."""
    return AIProvenance(
        model=model,
        provider=provider,
        correlation_id=correlation_id,
    )


def get_ml_provenance(
    model_type: str,
    correlation_id: str | None = None,
) -> AIProvenance:
    """Return provenance for locally-trained ML model outputs."""
    return AIProvenance(
        model=model_type,
        provider="sentinel-local",
        correlation_id=correlation_id,
    )


# ---------------------------------------------------------------------------
# HTTP header helpers
# ---------------------------------------------------------------------------


def provenance_headers(provenance: AIProvenance) -> dict[str, str]:
    """Convert provenance into HTTP response headers.

    Headers returned:
        X-AI-Generated  – always "true"
        X-AI-Model      – model identifier
        X-AI-Provider   – provider name
        X-AI-Disclosure – human-readable disclosure text
    """
    return {
        "X-AI-Generated": str(provenance.ai_generated).lower(),
        "X-AI-Model": provenance.model,
        "X-AI-Provider": provenance.provider,
        "X-AI-Disclosure": provenance.disclosure,
        "X-App-Version": provenance.app_version,
        "X-Config-Checksum": provenance.config_checksum,
    }


def runtime_metadata() -> dict[str, str]:
    """Return runtime version metadata for body-level stamping."""
    return {
        "app_version": settings.app_version,
        "config_checksum": settings.config_checksum,
    }


def attach_runtime_metadata(payload: Any) -> Any:
    """Attach runtime version metadata to a response payload.

    Dict payloads receive top-level metadata.
    List payloads preserve shape and stamp each dict item.
    """
    metadata = runtime_metadata()
    return _attach_metadata(payload, metadata)


def attach_ai_provenance(payload: Any, provenance: AIProvenance) -> Any:
    """Attach runtime version metadata and AI provenance to a response payload."""
    metadata = runtime_metadata()
    metadata["ai_provenance"] = provenance.model_dump()
    return _attach_metadata(payload, metadata)


def _attach_metadata(payload: Any, metadata: dict[str, Any]) -> Any:
    """Attach metadata to dict payloads or dict items in lists."""
    if isinstance(payload, BaseModel):
        payload = payload.model_dump()

    if isinstance(payload, dict):
        stamped = dict(payload)
        for key, value in metadata.items():
            stamped.setdefault(key, value)
        return stamped

    if isinstance(payload, list):
        stamped_items = []
        for item in payload:
            if isinstance(item, BaseModel):
                item = item.model_dump()
            if isinstance(item, dict):
                stamped_item = dict(item)
                for key, value in metadata.items():
                    stamped_item.setdefault(key, value)
                stamped_items.append(stamped_item)
            else:
                stamped_items.append(item)
        return stamped_items

    return payload
