"""AI Provenance utility for EU AI Act Article 50 transparency compliance.

Every API response containing AI-generated content must include provenance
metadata identifying the content as AI-generated, the model used, and the
provider.  This module provides the shared data model and helper functions
used across all AI-facing endpoints.
"""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class AIProvenance(BaseModel):
    """Article 50 transparency metadata attached to AI-generated responses."""

    ai_generated: bool = True
    model: str  # e.g. "claude-sonnet-4-20250514", "lstm-chiller-v1"
    provider: str  # e.g. "anthropic", "sentinel-local"
    disclosure: str = (
        "This content was generated by an AI system (SENTINEL). "
        "It should be reviewed by qualified personnel before acting on it."
    )
    correlation_id: Optional[str] = None


# ---------------------------------------------------------------------------
# Convenience constructors
# ---------------------------------------------------------------------------


def get_claude_provenance(correlation_id: Optional[str] = None) -> AIProvenance:
    """Return provenance for Claude-generated content (chat, explanations)."""
    return AIProvenance(
        model="claude-sonnet-4-20250514",
        provider="anthropic",
        correlation_id=correlation_id,
    )


def get_local_llm_provenance(
    model: str = "phi3:mini",
    correlation_id: Optional[str] = None,
) -> AIProvenance:
    """Return provenance for local LLM-generated content (Ollama/local runtime)."""
    return AIProvenance(
        model=model,
        provider="sentinel-local",
        correlation_id=correlation_id,
    )


def get_cloud_llm_provenance(
    provider: str,
    model: str,
    correlation_id: Optional[str] = None,
) -> AIProvenance:
    """Return provenance for cloud LLM-generated content."""
    return AIProvenance(
        model=model,
        provider=provider,
        correlation_id=correlation_id,
    )


def get_ml_provenance(
    model_type: str,
    correlation_id: Optional[str] = None,
) -> AIProvenance:
    """Return provenance for locally-trained ML model outputs."""
    return AIProvenance(
        model=model_type,
        provider="sentinel-local",
        correlation_id=correlation_id,
    )


# ---------------------------------------------------------------------------
# HTTP header helpers
# ---------------------------------------------------------------------------


def provenance_headers(provenance: AIProvenance) -> dict[str, str]:
    """Convert provenance into HTTP response headers.

    Headers returned:
        X-AI-Generated  – always "true"
        X-AI-Model      – model identifier
        X-AI-Provider   – provider name
        X-AI-Disclosure – human-readable disclosure text
    """
    return {
        "X-AI-Generated": str(provenance.ai_generated).lower(),
        "X-AI-Model": provenance.model,
        "X-AI-Provider": provenance.provider,
        "X-AI-Disclosure": provenance.disclosure,
    }
