-- ============================================================================
-- Space Occupancy POC — Fairland 2 (FLN02) 5-room pilot
-- Migration: space_occupancy_poc.sql
-- Created: 2026-03-08
-- ============================================================================

-- Registered sensor devices (one per room)
CREATE TABLE IF NOT EXISTS space_sensor_devices (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    device_token    TEXT NOT NULL UNIQUE,
    room_code       TEXT NOT NULL,
    sensor_id       TEXT NOT NULL UNIQUE,
    site_id         TEXT NOT NULL DEFAULT 'FLN02',
    enabled         BOOLEAN NOT NULL DEFAULT true,
    firmware_version TEXT,
    last_seen_at    TIMESTAMPTZ,
    last_rssi       INTEGER,
    uptime_seconds  INTEGER,
    sensor_online   BOOLEAN NOT NULL DEFAULT false,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_space_sensor_devices_site ON space_sensor_devices(site_id);
CREATE INDEX IF NOT EXISTS idx_space_sensor_devices_room ON space_sensor_devices(room_code);

-- Raw sensor events (append-only log)
CREATE TABLE IF NOT EXISTS space_room_events (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    room_code       TEXT NOT NULL,
    sensor_id       TEXT NOT NULL,
    occupied        BOOLEAN NOT NULL,
    event_type      TEXT NOT NULL CHECK (event_type IN ('state_change', 'heartbeat')),
    rssi            INTEGER,
    uptime_seconds  INTEGER,
    firmware_version TEXT,
    timestamp       TIMESTAMPTZ NOT NULL,
    received_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    site_id         TEXT NOT NULL DEFAULT 'FLN02'
);

CREATE INDEX IF NOT EXISTS idx_space_room_events_room ON space_room_events(room_code, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_space_room_events_site ON space_room_events(site_id);

-- Materialised current state per room (upserted on each event)
CREATE TABLE IF NOT EXISTS space_room_current_state (
    room_code           TEXT PRIMARY KEY,
    site_id             TEXT NOT NULL DEFAULT 'FLN02',
    occupied            BOOLEAN NOT NULL DEFAULT false,
    last_event_type     TEXT,
    last_state_change_at TIMESTAMPTZ,
    last_heartbeat_at   TIMESTAMPTZ,
    occupied_since      TIMESTAMPTZ,
    empty_since         TIMESTAMPTZ,
    sensor_online       BOOLEAN NOT NULL DEFAULT false,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Findings generated by the rules engine
CREATE TABLE IF NOT EXISTS space_room_state_findings (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    room_code       TEXT NOT NULL,
    site_id         TEXT NOT NULL DEFAULT 'FLN02',
    finding_type    TEXT NOT NULL,
    detail          TEXT,
    occupied_at     TIMESTAMPTZ,
    detected_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved        BOOLEAN NOT NULL DEFAULT false,
    resolved_at     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_space_findings_room ON space_room_state_findings(room_code);
CREATE INDEX IF NOT EXISTS idx_space_findings_active ON space_room_state_findings(resolved) WHERE NOT resolved;

-- ============================================================================
-- Seed: 5 Fairland 2 meeting-room sensors (LD2410C mmWave)
-- ============================================================================
INSERT INTO space_sensor_devices (device_token, room_code, sensor_id, site_id, enabled)
VALUES
    ('tkn_FA2-1Q1-MR-01_a3f9c2', 'FA2-1Q1-MR-01', 'LD2410C-FA2-1Q1-MR-01', 'FLN02', true),
    ('tkn_FA2-1Q1-MR-02_b7e4d1', 'FA2-1Q1-MR-02', 'LD2410C-FA2-1Q1-MR-02', 'FLN02', true),
    ('tkn_FA2-1Q1-MR-05_c2a8f5', 'FA2-1Q1-MR-05', 'LD2410C-FA2-1Q1-MR-05', 'FLN02', true),
    ('tkn_FA2-1Q1-MR-06_d9b3e7', 'FA2-1Q1-MR-06', 'LD2410C-FA2-1Q1-MR-06', 'FLN02', true),
    ('tkn_FA2-1Q2-MR-08_e5c6a9', 'FA2-1Q2-MR-08', 'LD2410C-FA2-1Q2-MR-08', 'FLN02', true)
ON CONFLICT (device_token) DO NOTHING;
