"""Brick Ontology Runtime Service.

Provides fast graph traversal and context enrichment using the Brick graph
and resolution index generated by brick_autogen_service.py.

Two main functions:
1. resolve_point(bacnet_ref) -> (point_iri, equipment_iri)
2. get_context(equipment_id) -> BrickEquipmentContext

See: docs/02-architecture/brick-ontology-layer.md
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

try:
    from rdflib import Graph, Literal, Namespace, URIRef
    from rdflib.namespace import RDF, RDFS

    RDFLIB_AVAILABLE = True
except ImportError:
    RDFLIB_AVAILABLE = False

logger = logging.getLogger(__name__)

# Namespaces (must match brick_autogen_service.py)
if RDFLIB_AVAILABLE:
    BRICK = Namespace("https://brickschema.org/schema/Brick#")
    REF = Namespace("https://brickschema.org/schema/Brick/ref#")
    BACNET = Namespace("https://brickschema.org/schema/Brick/ref/bacnet#")
    SENTINEL = Namespace("urn:sentinel:")
else:
    BRICK = REF = BACNET = SENTINEL = None  # type: ignore[assignment]


# ---------------------------------------------------------------------------
# Data contracts
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class BrickPointRef:
    """A point resolved from the Brick graph."""

    point_iri: str
    label: str | None = None
    brick_class: str | None = None
    bacnet_ref: str | None = None
    bacnet_object_identifier: str | None = None  # "analogInput,1000"
    unit: str | None = None
    writable: bool | None = None
    point_type: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "point_iri": self.point_iri,
            "label": self.label,
            "brick_class": self.brick_class,
            "bacnet_ref": self.bacnet_ref,
            "bacnet_object_identifier": self.bacnet_object_identifier,
            "unit": self.unit,
            "writable": self.writable,
            "point_type": self.point_type,
        }


@dataclass
class BrickEquipmentContext:
    """Full context for one equipment item from the Brick graph."""

    equipment_iri: str
    equipment_id: str
    equipment_type: str | None = None
    label: str | None = None
    protocol: str | None = None
    manufacturer: str | None = None
    model: str | None = None
    location_iri: str | None = None
    location_path: list[tuple[str, str]] = field(default_factory=list)
    points: list[BrickPointRef] = field(default_factory=list)
    # Reserved for hybrid_query_service enrichment
    vendor: dict[str, Any] | None = None
    contract: dict[str, Any] | None = None
    documents: list[dict[str, Any]] | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "equipment_iri": self.equipment_iri,
            "equipment_id": self.equipment_id,
            "equipment_type": self.equipment_type,
            "label": self.label,
            "protocol": self.protocol,
            "manufacturer": self.manufacturer,
            "model": self.model,
            "location_iri": self.location_iri,
            "location_path": [{"iri": iri, "label": lbl} for iri, lbl in self.location_path],
            "points": [p.to_dict() for p in self.points],
            "vendor": self.vendor,
            "contract": self.contract,
            "documents": self.documents,
        }


# ---------------------------------------------------------------------------
# Brick Service
# ---------------------------------------------------------------------------
class BrickService:
    """Runtime service for Brick graph traversal and equipment context lookup."""

    def __init__(
        self,
        *,
        brick_ttl_path: Path,
        resolution_index_path: Path,
    ) -> None:
        if not RDFLIB_AVAILABLE:
            raise ImportError("rdflib is required for BrickService")

        self.brick_ttl_path = brick_ttl_path
        self.resolution_index_path = resolution_index_path

        # Load graph
        self.g = Graph()
        self.g.parse(str(brick_ttl_path), format="turtle")
        logger.info("Loaded Brick graph from %s (%d triples)", brick_ttl_path, len(self.g))

        # Load resolution index
        raw_idx = json.loads(resolution_index_path.read_text(encoding="utf-8"))
        self.bacnet_ref_to_point: dict[str, str] = raw_idx.get("bacnet_ref_to_point_iri", {})
        self.bacnet_object_to_point: dict[str, str] = raw_idx.get("bacnet_object_to_point_iri", {})
        self.point_to_equipment: dict[str, str] = raw_idx.get("point_iri_to_equipment_iri", {})
        self.equipment_code_to_iri: dict[str, str] = raw_idx.get("equipment_code_to_equipment_iri", {})
        self.equipment_code_to_loc: dict[str, str] = raw_idx.get("equipment_code_to_location_iri", {})

    # -------------------------------------------------------------------
    # 1) resolve_point: bacnet_ref or object_type,instance -> equipment
    # -------------------------------------------------------------------
    def resolve_point(
        self,
        *,
        bacnet_ref: str | None = None,
        object_type: str | None = None,
        instance: int | None = None,
    ) -> tuple[str, str] | None:
        """Resolve a BACnet point to (point_iri, equipment_iri).

        Args:
            bacnet_ref: BMS-native point reference (e.g., "CH-1.ChwSupplyTemp")
            object_type: BACnet object type (e.g., "analogInput")
            instance: BACnet instance number (e.g., 1000)

        Returns:
            (point_iri, equipment_iri) or None if not found
        """
        point_iri = None

        # Try bacnet_ref lookup first (fastest)
        if bacnet_ref:
            point_iri = self.bacnet_ref_to_point.get(bacnet_ref)

        # Try object_type,instance lookup
        if not point_iri and object_type is not None and instance is not None:
            key = f"{str(object_type).lower()},{int(instance)}"
            point_iri = self.bacnet_object_to_point.get(key)

        # Fallback: graph search by bacnet_ref literal
        if not point_iri and bacnet_ref:
            point_iri = self._graph_search_bacnet_ref(bacnet_ref)

        if not point_iri:
            return None

        # Resolve to equipment
        equipment_iri = self.point_to_equipment.get(point_iri)
        if not equipment_iri:
            equipment_iri = self._graph_equipment_for_point(point_iri)

        if not equipment_iri:
            return None

        return point_iri, equipment_iri

    def resolve_equipment_id(
        self,
        *,
        bacnet_ref: str | None = None,
        object_type: str | None = None,
        instance: int | None = None,
    ) -> str | None:
        """Convenience: resolve a point all the way to equipment_id string."""
        result = self.resolve_point(
            bacnet_ref=bacnet_ref,
            object_type=object_type,
            instance=instance,
        )
        if not result:
            return None
        _, equipment_iri = result
        # Reverse lookup equipment code from IRI
        for code, iri in self.equipment_code_to_iri.items():
            if iri == equipment_iri:
                return code
        # Extract from IRI pattern sentinel:eq/{code}
        if "/eq/" in equipment_iri:
            return equipment_iri.split("/eq/")[-1]
        return None

    # -------------------------------------------------------------------
    # 2) get_context: equipment_id -> full context
    # -------------------------------------------------------------------
    def get_context(
        self,
        equipment_id: str,
        *,
        include_points: bool = True,
    ) -> BrickEquipmentContext | None:
        """Get full Brick context for an equipment item.

        Args:
            equipment_id: Equipment code (e.g., "S002-CHILLER-B1-001")
            include_points: Whether to include point details

        Returns:
            BrickEquipmentContext or None if equipment not in graph
        """
        equipment_iri = self.equipment_code_to_iri.get(equipment_id)
        if not equipment_iri:
            # Try constructing IRI directly
            equipment_iri = str(URIRef(SENTINEL[f"eq/{equipment_id}"]))

        # Check equipment exists in graph
        if not any(self.g.triples((URIRef(equipment_iri), None, None))):
            return None

        label = self._label(equipment_iri)
        equipment_type = self._brick_class_local_name(equipment_iri)
        protocol = self._literal(equipment_iri, SENTINEL.protocol)
        manufacturer = self._literal(equipment_iri, SENTINEL.manufacturer)
        model = self._literal(equipment_iri, SENTINEL.model)

        # Location
        location_iri = self.equipment_code_to_loc.get(equipment_id)
        if not location_iri:
            for _, _, loc in self.g.triples((URIRef(equipment_iri), BRICK.hasLocation, None)):
                location_iri = str(loc)
                break

        location_path = self._walk_location_path(location_iri) if location_iri else []

        # Points
        points: list[BrickPointRef] = []
        if include_points:
            points = self._collect_points(equipment_iri)

        return BrickEquipmentContext(
            equipment_iri=equipment_iri,
            equipment_id=equipment_id,
            equipment_type=equipment_type,
            label=label,
            protocol=protocol,
            manufacturer=manufacturer,
            model=model,
            location_iri=location_iri,
            location_path=location_path,
            points=points,
        )

    def list_equipment(self) -> list[str]:
        """List all equipment IDs in the graph."""
        return sorted(self.equipment_code_to_iri.keys())

    # -------------------------------------------------------------------
    # Graph helpers
    # -------------------------------------------------------------------
    def _label(self, iri: str) -> str | None:
        for _, _, o in self.g.triples((URIRef(iri), RDFS.label, None)):
            if isinstance(o, Literal):
                return str(o)
        return None

    def _literal(self, iri: str, predicate: URIRef) -> str | None:
        for _, _, o in self.g.triples((URIRef(iri), predicate, None)):
            return str(o)
        return None

    def _bool_literal(self, iri: str, predicate: URIRef) -> bool | None:
        val = self._literal(iri, predicate)
        if val is None:
            return None
        return val.strip().lower() in ("true", "1")

    def _brick_class_local_name(self, iri: str) -> str | None:
        """Get the Brick class local name (e.g., 'Chiller') for an entity."""
        brick_ns = str(BRICK)
        for _, _, o in self.g.triples((URIRef(iri), RDF.type, None)):
            s = str(o)
            if s.startswith(brick_ns):
                return s[len(brick_ns) :]
        return None

    def _graph_search_bacnet_ref(self, bacnet_ref: str) -> str | None:
        """Fallback: search graph for a point with matching bacnet_ref."""
        # Check sentinel:bacnet_ref on point nodes
        for s, _, o in self.g.triples((None, SENTINEL.bacnet_ref, Literal(bacnet_ref))):
            # Could be on point directly or on external ref node
            # If on point, return it
            if any(self.g.triples((s, BRICK.isPointOf, None))):
                return str(s)
            # If on external ref node, find the point that owns it
            for pt, _, _ in self.g.triples((None, REF.hasExternalReference, s)):
                return str(pt)

        # Check bacnet:object-name on external ref nodes
        for refnode, _, o in self.g.triples((None, BACNET["object-name"], Literal(bacnet_ref))):
            for pt, _, _ in self.g.triples((None, REF.hasExternalReference, refnode)):
                return str(pt)

        return None

    def _graph_equipment_for_point(self, point_iri: str) -> str | None:
        """Fallback: find equipment for a point via graph traversal."""
        for _, _, eq in self.g.triples((URIRef(point_iri), BRICK.isPointOf, None)):
            return str(eq)
        for eq, _, _ in self.g.triples((None, BRICK.hasPoint, URIRef(point_iri))):
            return str(eq)
        return None

    def _collect_points(self, equipment_iri: str) -> list[BrickPointRef]:
        """Collect all points for an equipment item."""
        points: list[BrickPointRef] = []

        for _, _, pt in self.g.triples((URIRef(equipment_iri), BRICK.hasPoint, None)):
            pt_iri = str(pt)

            # Get bacnet_ref from point or external ref node
            bacnet_ref = self._literal(pt_iri, SENTINEL.bacnet_ref)
            if not bacnet_ref:
                for _, _, refnode in self.g.triples((URIRef(pt_iri), REF.hasExternalReference, None)):
                    bacnet_ref = self._literal(str(refnode), SENTINEL.bacnet_ref)
                    if not bacnet_ref:
                        bacnet_ref = self._literal(str(refnode), BACNET["object-name"])
                    if bacnet_ref:
                        break

            # Get BACnet object identifier from external ref
            bacnet_oid = None
            for _, _, refnode in self.g.triples((URIRef(pt_iri), REF.hasExternalReference, None)):
                oid = self._literal(str(refnode), BACNET["object-identifier"])
                if oid:
                    bacnet_oid = oid
                    break

            points.append(
                BrickPointRef(
                    point_iri=pt_iri,
                    label=self._label(pt_iri),
                    brick_class=self._brick_class_local_name(pt_iri),
                    bacnet_ref=bacnet_ref,
                    bacnet_object_identifier=bacnet_oid,
                    unit=self._literal(pt_iri, SENTINEL.unit),
                    writable=self._bool_literal(pt_iri, SENTINEL.writable),
                    point_type=self._literal(pt_iri, SENTINEL.point_type),
                )
            )

        # Stable sort for deterministic prompt output
        points.sort(key=lambda p: (p.bacnet_ref or "", p.label or "", p.point_iri))
        return points

    def _walk_location_path(self, location_iri: str) -> list[tuple[str, str]]:
        """Walk from leaf location up to site root via inverse hasPart."""
        path: list[tuple[str, str]] = []
        cur = URIRef(location_iri)
        seen: set = set()

        while cur and str(cur) not in seen:
            seen.add(str(cur))
            label = self._label(str(cur)) or str(cur).rsplit("/", 1)[-1]
            path.append((str(cur), label))

            # Find parent: parent brick:hasPart cur
            parent = None
            for p, _, _ in self.g.triples((None, BRICK.hasPart, cur)):
                parent = p
                break
            cur = parent

        path.reverse()  # Root (site) first
        return path


# ---------------------------------------------------------------------------
# Singleton loader
# ---------------------------------------------------------------------------
_instance: BrickService | None = None


def get_brick_service(
    site_id: str = "site-002",
    base_dir: Path | None = None,
) -> BrickService | None:
    """Get or create BrickService singleton for a site.

    Returns None if Brick artifacts don't exist yet.
    """
    global _instance

    if _instance is not None:
        return _instance

    if base_dir is None:
        base_dir = Path(__file__).parent.parent.parent  # backend/

    brick_dir = base_dir / "app" / "data" / "buildings" / site_id / "brick"
    ttl_path = brick_dir / f"{site_id}_brick.ttl"
    idx_path = brick_dir / f"{site_id}_resolution_index.json"

    if not ttl_path.exists() or not idx_path.exists():
        logger.info("Brick artifacts not found for %s (run brick_autogen_service first)", site_id)
        return None

    try:
        _instance = BrickService(
            brick_ttl_path=ttl_path,
            resolution_index_path=idx_path,
        )
        return _instance
    except Exception as e:
        logger.warning("Failed to load BrickService for %s: %s", site_id, e)
        return None
