-- Migration: Energy Consumption History
-- Description: Time-series energy consumption data for dashboard analytics
-- Date: 2026-02-01

-- Table: energy_consumption_history
-- Stores daily energy consumption by category (HVAC, Lighting, Other) per site
-- Used for energy consumption charts and analytics

CREATE TABLE IF NOT EXISTS energy_consumption_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_id TEXT NOT NULL,  -- Building code (e.g., "site-002", "demo-office")
    date DATE NOT NULL,
    hvac_kwh NUMERIC(10, 2) NOT NULL DEFAULT 0,
    lighting_kwh NUMERIC(10, 2) NOT NULL DEFAULT 0,
    other_kwh NUMERIC(10, 2) NOT NULL DEFAULT 0,
    total_kwh NUMERIC(10, 2) NOT NULL GENERATED ALWAYS AS (hvac_kwh + lighting_kwh + other_kwh) STORED,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for query performance
CREATE INDEX IF NOT EXISTS idx_energy_consumption_history_building_date
    ON energy_consumption_history(building_id, date DESC);

CREATE INDEX IF NOT EXISTS idx_energy_consumption_history_date
    ON energy_consumption_history(date DESC);

-- Unique constraint to prevent duplicate entries
CREATE UNIQUE INDEX IF NOT EXISTS idx_energy_consumption_history_building_date_unique
    ON energy_consumption_history(building_id, date);

-- Updated at trigger
CREATE OR REPLACE FUNCTION update_energy_consumption_history_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_energy_consumption_history_updated_at
    BEFORE UPDATE ON energy_consumption_history
    FOR EACH ROW
    EXECUTE FUNCTION update_energy_consumption_history_updated_at();

-- Comments
COMMENT ON TABLE energy_consumption_history IS 'Daily energy consumption by category for dashboard analytics';
COMMENT ON COLUMN energy_consumption_history.building_id IS 'Building code (e.g., site-002, demo-office)';
COMMENT ON COLUMN energy_consumption_history.date IS 'Consumption date';
COMMENT ON COLUMN energy_consumption_history.hvac_kwh IS 'HVAC energy consumption in kWh';
COMMENT ON COLUMN energy_consumption_history.lighting_kwh IS 'Lighting energy consumption in kWh';
COMMENT ON COLUMN energy_consumption_history.other_kwh IS 'Other equipment energy consumption in kWh';
COMMENT ON COLUMN energy_consumption_history.total_kwh IS 'Total energy consumption (computed)';
