-- 048_municipal_demand_history.sql
-- Simulated maximum demand history for municipal billing (demo data)

CREATE TABLE IF NOT EXISTS municipal_demand_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id TEXT NOT NULL,
    meter_id TEXT,
    date DATE NOT NULL,
    peak_demand_kw NUMERIC(12, 2) NOT NULL DEFAULT 0,
    peak_demand_kva NUMERIC(12, 2) NOT NULL DEFAULT 0,
    peak_timestamp TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_municipal_demand_site_date
    ON municipal_demand_history(site_id, date DESC);

CREATE INDEX IF NOT EXISTS idx_municipal_demand_meter_date
    ON municipal_demand_history(meter_id, date DESC);

-- Seed demo data for site-002 (last 30 days)
DO $$
DECLARE
    d DATE := CURRENT_DATE - INTERVAL '29 days';
    base_kw NUMERIC := 450;
    variance NUMERIC;
    peak_time TIMESTAMPTZ;
BEGIN
    WHILE d <= CURRENT_DATE LOOP
        variance := (random() * 80) - 40; -- +/- 40 kW
        peak_time := d::timestamp + interval '18 hours' + (random() * interval '2 hours');
        INSERT INTO municipal_demand_history (
            site_id,
            meter_id,
            date,
            peak_demand_kw,
            peak_demand_kva,
            peak_timestamp
        ) VALUES (
            'site-002',
            'S002-MTR-E-MAIN',
            d,
            ROUND(base_kw + variance, 2),
            ROUND((base_kw + variance) * 1.05, 2),
            peak_time
        );
        d := d + INTERVAL '1 day';
    END LOOP;
END $$;

-- Seed demo data for site-004 (last 30 days)
DO $$
DECLARE
    d DATE := CURRENT_DATE - INTERVAL '29 days';
    base_kw NUMERIC := 320;
    variance NUMERIC;
    peak_time TIMESTAMPTZ;
BEGIN
    WHILE d <= CURRENT_DATE LOOP
        variance := (random() * 60) - 30; -- +/- 30 kW
        peak_time := d::timestamp + interval '17 hours' + (random() * interval '2 hours');
        INSERT INTO municipal_demand_history (
            site_id,
            meter_id,
            date,
            peak_demand_kw,
            peak_demand_kva,
            peak_timestamp
        ) VALUES (
            'site-004',
            'S004-MTR-E-MAIN',
            d,
            ROUND(base_kw + variance, 2),
            ROUND((base_kw + variance) * 1.05, 2),
            peak_time
        );
        d := d + INTERVAL '1 day';
    END LOOP;
END $$;
